package de.lasttest.domain

import org.slf4j.LoggerFactory
import java.util.Base64
import javax.crypto.Cipher
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * [TestRunPayloadEncryptor] backed by AES in Galois/Counter Mode
 * (GCM) with a 256-bit key. GCM is an authenticated-encryption
 * mode so a tampered ciphertext cannot be silently round-tripped
 * to the original plaintext — the 128-bit authentication tag is
 * verified on every [decrypt] call, and a mismatch is reported
 * as a decryption error rather than producing garbage output.
 *
 * The on-the-wire layout of the encrypted blob is:
 *
 * ```
 *   "LENC"            // 4 ASCII bytes, magic prefix
 *   0x01              // 1 byte, version — bumped if the format changes
 *   iv (12 bytes)     // fresh IV per call, generated by SecureRandom
 *   ciphertext        // variable length
 *   gcm tag (16 bytes)// appended by the JCE GCM implementation
 * ```
 *
 * The whole thing is Base64-encoded (URL-safe, no padding) so it
 * fits into a single `VARCHAR` / `CLOB` column without escaping
 * problems and the H2 console can still display it as text.
 *
 * The magic prefix is the read-side discriminator between an
 * encrypted blob and a plaintext legacy row: a column written by
 * an older build carries plain JSON and never starts with `LENC`,
 * so the [decrypt] fast-path returns the input unchanged. This
 * lets the encryption feature ship without a one-shot
 * migration of the existing H2 file — new writes are encrypted,
 * old reads keep working, and the rows are upgraded in place the
 * next time the run is rewritten to a terminal state.
 */
class AesGcmTestRunPayloadEncryptor(
    private val key: SecretKey,
) : TestRunPayloadEncryptor {
    /**
     * Lazily-resolved [Cipher] instance. [Cipher] is not
     * thread-safe, so each call grabs a fresh instance rather
     * than reusing one across threads. Allocation cost is
     * negligible compared to the AES work itself.
     */
    private fun cipher(): Cipher = Cipher.getInstance(TRANSFORMATION)

    override fun encrypt(plain: String?): String? {
        if (plain == null) return null
        val iv = randomBytes(IV_LENGTH)
        val cipher = cipher()
        cipher.init(Cipher.ENCRYPT_MODE, key, GCMParameterSpec(TAG_LENGTH_BITS, iv))
        val ciphertext = cipher.doFinal(plain.toByteArray(Charsets.UTF_8))
        val out = ByteArray(MAGIC.size + VERSION.size + iv.size + ciphertext.size)
        var offset = 0
        System.arraycopy(MAGIC, 0, out, offset, MAGIC.size)
        offset += MAGIC.size
        System.arraycopy(VERSION, 0, out, offset, VERSION.size)
        offset += VERSION.size
        System.arraycopy(iv, 0, out, offset, iv.size)
        offset += iv.size
        System.arraycopy(ciphertext, 0, out, offset, ciphertext.size)
        return Base64.getUrlEncoder().withoutPadding().encodeToString(out)
    }

    override fun decrypt(blob: String?): String? {
        if (blob == null) return null
        // Fast path for legacy plaintext rows: anything that does
        // not start with the Base64-encoded magic prefix is
        // treated as already-decrypted JSON. Skipping the Base64
        // decode avoids a spurious "illegal base64 character"
        // error for a JSON document that legitimately starts
        // with `{` or `[`.
        if (!blob.startsWith(ENCODED_MAGIC_PREFIX)) return blob
        val bytes =
            try {
                Base64.getUrlDecoder().decode(blob)
            } catch (exception: IllegalArgumentException) {
                // A blob that begins with the magic but is not
                // valid Base64 cannot be decrypted — log once and
                // return the input unchanged so the mapper at
                // least surfaces a meaningful (if unparseable)
                // value to the user.
                log.warn("Blob beginnt mit Verschlüsselungs-Magic, ist aber kein gültiges Base64: {}", exception.message)
                return blob
            }
        if (bytes.size < MAGIC.size + VERSION.size + IV_LENGTH + TAG_LENGTH_BYTES) {
            log.warn("Verschlüsselter Blob ist zu kurz ({} Bytes) — gebe ihn unverändert zurück.", bytes.size)
            return blob
        }
        if (!MAGIC.contentEquals(bytes.copyOfRange(0, MAGIC.size))) {
            // The encoded prefix is part of the Base64 alphabet,
            // so a true match requires the raw bytes to match
            // the magic. Anything else is malformed.
            log.warn("Blob-Magic stimmt nach Base64-Decode nicht überein — gebe ihn unverändert zurück.")
            return blob
        }
        if (VERSION[0] != bytes[MAGIC.size]) {
            // Forward-compat hook: a future version can either
            // fall back to a different decoder here, or refuse
            // the blob outright. For now we only know how to
            // decrypt version 0x01, so anything else is rejected.
            log.warn("Unbekannte Verschlüsselungs-Version 0x{} — gebe Blob unverändert zurück.", bytes[MAGIC.size])
            return blob
        }
        val iv = bytes.copyOfRange(MAGIC.size + VERSION.size, MAGIC.size + VERSION.size + IV_LENGTH)
        val payload = bytes.copyOfRange(MAGIC.size + VERSION.size + IV_LENGTH, bytes.size)
        val cipher = cipher()
        return try {
            cipher.init(Cipher.DECRYPT_MODE, key, GCMParameterSpec(TAG_LENGTH_BITS, iv))
            String(cipher.doFinal(payload), Charsets.UTF_8)
        } catch (exception: Exception) {
            // The two realistic failures are: wrong key
            // (AEADBadTagException) and tampered ciphertext.
            // Either way we cannot recover the plaintext, and
            // the mapper at the call site treats a `null`
            // return as "no configuration available", so the
            // user sees an empty report rather than a crash.
            log.warn("Entschlüsselung fehlgeschlagen ({}): {}. Gebe null zurück.", exception::class.java.simpleName, exception.message)
            null
        }
    }

    private companion object {
        const val TRANSFORMATION: String = "AES/GCM/NoPadding"
        const val IV_LENGTH: Int = 12
        const val TAG_LENGTH_BITS: Int = 128
        const val TAG_LENGTH_BYTES: Int = TAG_LENGTH_BITS / 8

        // 4-byte ASCII magic so the encrypt/decrypt formats stay
        // recognisable in a hex-dump of the H2 file. The values
        // spell "LENC" (lasttest encrypted).
        val MAGIC: ByteArray = byteArrayOf(0x4C, 0x45, 0x4E, 0x43)
        val VERSION: ByteArray = byteArrayOf(0x01)

        // Base64 form of [MAGIC] (URL-safe, no padding) used as
        // the fast-path discriminator on the read path. Keeping
        // it precomputed means the decryptor does not have to
        // encode the magic on every call to recognise an
        // encrypted blob.
        const val ENCODED_MAGIC_PREFIX: String = "TEVOQ"

        private val log = LoggerFactory.getLogger(AesGcmTestRunPayloadEncryptor::class.java)
    }
}

/**
 * Cryptographically-strong random byte source. Wraps
 * [java.security.SecureRandom] in a helper so the call sites in
 * [AesGcmTestRunPayloadEncryptor.encrypt] stay focused on the
 * wire-format assembly.
 */
private fun randomBytes(length: Int): ByteArray {
    val out = ByteArray(length)
    SECURE_RANDOM.nextBytes(out)
    return out
}

private val SECURE_RANDOM: java.security.SecureRandom = java.security.SecureRandom()
