export type ReportParameterValue = {
  name: string
  location: string
  value: string
}

export type ReportOperation = {
  operationId: string
  method: string
  path: string
  summary: string
  parameterValues: ReportParameterValue[]
  requestBodyJson?: string
  bearerTokenConfigured: boolean
}

export type TestRunConfiguration = {
  apiTitle: string
  apiVersion: string
  baseUrl: string
  virtualUsers: number
  durationSeconds: number
  useIterations: boolean
  operations: ReportOperation[]
}

export type TestRun = {
  id: string
  status: string
  createdAt: string
  startedAt?: string
  finishedAt?: string
  exitCode?: number
  configuration?: TestRunConfiguration
  summary?: { raw: string }
  error?: string
}

export type K6Metric = {
  avg?: number
  min?: number
  med?: number
  max?: number
  'p(90)'?: number
  'p(95)'?: number
  count?: number
  rate?: number
  value?: number
  passes?: number
  fails?: number
  thresholds?: Record<string, boolean>
}

export type K6Summary = {
  metrics: Record<string, K6Metric>
  root_group?: {
    checks?: Record<string, { name: string, passes: number, fails: number }>
  }
}

export function parseK6Summary(run: TestRun): K6Summary | undefined {
  if (!run.summary?.raw) return undefined
  try {
    const parsed: unknown = JSON.parse(run.summary.raw)
    if (!isRecord(parsed) || !isRecord(parsed.metrics)) return undefined
    return parsed as K6Summary
  } catch {
    return undefined
  }
}

export function metric(summary: K6Summary, name: string): K6Metric {
  return summary.metrics[name] ?? {}
}

export function completedRequestCount(summary: K6Summary): number | undefined {
  const count = metric(summary, 'http_reqs').count
  return count != null && Number.isFinite(count) ? count : undefined
}

// Per-operation status-code counts extracted from the Counter metrics
// generated by `DefaultK6ScriptGenerator`. The metric name format is
// `lt_status_{<code>|err|other}_<operationId>`, where `<code>` is one
// of TRACKED_STATUS_CODES (e.g. 200, 401, 429) and `err` covers
// network errors (status === 0). `other` catches any status code
// that the generator did not pre-declare, so unexpected responses
// still surface in the report.
//
// k6's --summary-export does NOT expose tagged sub-metrics, which is
// why the generator declares one Counter per (operation, code) tuple
// rather than tagging a single Counter per operation.
export const TRACKED_STATUS_CODES = [
  200, 201, 202, 204, // 2xx success
  301, 302, 304, // 3xx redirect
  400, 401, 403, 404, 409, 422, 429, // 4xx client error
  500, 502, 503, 504, // 5xx server error
] as const
export type TrackedStatusCode = (typeof TRACKED_STATUS_CODES)[number]

export const FALLBACK_CODES = ['err', 'other'] as const
export type FallbackCode = (typeof FALLBACK_CODES)[number]

// Every column the report knows about. We keep `err` last so the
// status-code columns stay grouped and the fallback columns visually
// detach from the main grid.
export const ALL_STATUS_CODES = [...TRACKED_STATUS_CODES, ...FALLBACK_CODES] as const
export type AllStatusCode = (typeof ALL_STATUS_CODES)[number]

export type StatusDistributionRow = {
  operationId: string
  // Indexed by string for ergonomic lookup in the React component.
  // Numeric keys are the tracked status codes, `"err"` and `"other"`
  // are the fallback buckets.
  counts: Record<string, number>
  total: number
}

// Build the row for a single operation. Counts default to 0 so the
// table is fully populated even when a particular code never fired.
export function statusDistribution(summary: K6Summary, operationIds: string[]): StatusDistributionRow[] {
  return operationIds.map(operationId => {
    const counts: Record<string, number> = {}
    let total = 0
    for (const code of ALL_STATUS_CODES) {
      const name = `lt_status_${code}_${operationId}`
      const value = metric(summary, name).count
      const safe = value != null && Number.isFinite(value) ? value : 0
      counts[String(code)] = safe
      total += safe
    }
    return { operationId, counts, total }
  })
}

// Returns the subset of status codes that fired at least once across
// all rows, keeping the original code order so the table columns stay
// stable between runs. Fallback columns (`err`, `other`) are always
// shown because the user wants to see at a glance whether there were
// network or unexpected responses.
export function activeStatusCodes(rows: StatusDistributionRow[]): (TrackedStatusCode | FallbackCode)[] {
  const seen = new Set<string>()
  for (const row of rows) {
    for (const [code, count] of Object.entries(row.counts)) {
      if (count > 0) seen.add(code)
    }
  }
  return ALL_STATUS_CODES.filter(code => {
    const key = String(code)
    if (FALLBACK_CODES.includes(code as FallbackCode)) return true
    return seen.has(key)
  })
}

export function checkSuccessRate(summary: K6Summary): number | undefined {
  const checks = metric(summary, 'checks')
  const total = (checks.passes ?? 0) + (checks.fails ?? 0)
  return total > 0 ? (checks.passes ?? 0) / total * 100 : undefined
}

export function formatNumber(value: number | undefined, digits = 2): string {
  if (value == null || !Number.isFinite(value)) return '–'
  return new Intl.NumberFormat('de-DE', {
    minimumFractionDigits: digits,
    maximumFractionDigits: digits,
  }).format(value)
}

export function formatInteger(value: number | undefined): string {
  if (value == null || !Number.isFinite(value)) return '–'
  return new Intl.NumberFormat('de-DE', { maximumFractionDigits: 0 }).format(value)
}

export function formatBytes(value: number | undefined): string {
  if (value == null || !Number.isFinite(value)) return '–'
  const units = ['B', 'KiB', 'MiB', 'GiB']
  let amount = value
  let unit = units[0]
  for (const candidate of units) {
    unit = candidate
    if (amount < 1024 || candidate === units.at(-1)) break
    amount /= 1024
  }
  return `${formatNumber(amount)} ${unit}`
}

export function formatTimestamp(value: string | undefined): string {
  if (!value) return '–'
  const date = new Date(value)
  if (Number.isNaN(date.getTime())) return '–'
  return new Intl.DateTimeFormat('de-DE', {
    dateStyle: 'medium',
    timeStyle: 'medium',
    timeZone: 'Europe/Berlin',
  }).format(date)
}

export function k6ScriptUrl(runId: string): string {
  return `/api/test-runs/${encodeURIComponent(runId)}/script`
}

export function k6ScriptDownloadName(runId: string): string {
  return `lasttest-${runId}.js`
}

export function manualK6Command(configuration: TestRunConfiguration | undefined, runId: string): string {
  const baseUrl = configuration?.baseUrl ?? 'https://target.example'
  return `k6 run -e BASE_URL=${JSON.stringify(baseUrl)} ${k6ScriptDownloadName(runId)}`
}

export async function copyTextToClipboard(text: string): Promise<boolean> {
  const clipboard = typeof navigator !== 'undefined' ? navigator.clipboard : undefined
  if (!clipboard?.writeText) return false
  try {
    await clipboard.writeText(text)
    return true
  } catch {
    return false
  }
}

export function operationDisplayPath(operation: ReportOperation): string {
  let path = operation.path
  for (const parameter of operation.parameterValues.filter(value => value.location === 'path')) {
    path = path.replace(`{${parameter.name}}`, parameter.value || `{${parameter.name}}`)
  }
  const query = operation.parameterValues
    .filter(value => value.location === 'query' && value.value.trim() !== '')
    .map(value => `${value.name}=${value.value}`)
    .join('&')
  return path + (query ? `?${query}` : '')
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
}
