spring.application.name=lasttest
server.address=0.0.0.0
server.port=8286
spring.web.resources.static-locations=classpath:/static/,file:${LASTTEST_FRONTEND_PATH:../frontend/dist}/
spring.mvc.static-path-pattern=/**
